title: "Analiza bezpieczenstwa KSeF"
description: "Analiza infrastruktury sieciowej, szyfrowania i roli Imperva WAF w Krajowym Systemie e-Faktur wykonana przy użyciu narzędzi AI"
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
